### ISSUE TITLE
miss files of example?

### ISSUE THREAD

**Issue by ghost** [facebookresearch/mvp#4]
Hi, I notice there are some discrepancies between the latest release and [README.md](https://github.com/facebookresearch/mvp#readme) and [mvp/ARCHITECTURE.md](https://github.com/facebookresearch/mvp/blob/main/ARCHITECTURE.md). 
Are there some files of example missing? Such as 'experiments/dryice1/experiment1/config.py' metioned in [README.md](https://github.com/facebookresearch/mvp#readme) or 'experiments/example/config.py' metioned in [mvp/ARCHITECTURE.md](https://github.com/facebookresearch/mvp/blob/main/ARCHITECTURE.md)? 
I follow the steps in [README.md](https://github.com/facebookresearch/mvp#readme) but can not train or render the model.

**Comment by stephenlombardi** [comment]
You'll want to download the experiments.zip file from the release here: https://github.com/facebookresearch/mvp/releases/tag/v0.1
