### ISSUE TITLE
Background image uesed in Lombardi‘s MVP not be found in multiface dataset

### ISSUE THREAD

**Issue by shuishiwojiade** [facebookresearch/mvp#9]
Multiface dataset has been used in "Mixture of Volumetric Primitives for Efficient Neural Rendering". The "mvp" onfig file needs the path to the background image. But I can't find the background image in multiface dataset.
The code in config file is: bgpath = os.path.join(imagepathbase, 'bg', image', 'cam{cam}', 'image0000.png').

**Comment by stephenlombardi** [comment]
Hi,

As noted by @cwuu, the background images are available [here](https://fb-baas-f32eacb9-8abb-11eb-b2b8-4857dd089e15.s3.amazonaws.com/MugsyDataRelease/MVP/bg_img.zip)

Note that these background images were extracted from the capture of the identity labeled, "002421669", so they will work best with that capture but they *should* work with any of the v2 captures (they may be missing some background images for some cameras however). 

Also note that bgpath is optional. You can pass None and it will try to learn the background images but without an initial guess.

**Comment by jackluchen** [comment]
Hi, thank you for such inspiring and marvelous work!

Do you have any plans to share the full background images (especially the V1 captures) in the near future?
